version: '3'
services:
    db:
        build: 
            context: ./src/db
        environment: 
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            GEOCODER_STATES: "${GEOCODER_STATES}"
            GEOCODER_YEAR: "${GEOCODER_YEAR}"
        ports:
            - "50001:5432"
        networks:
            uw_postgis_net:
                aliases:
                    - db
    api:
        build:
            context: ./src/server
        environment: 
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "50000:5000"
        depends_on:
            - db
        networks:
            uw_postgis_net:
                aliases:
                    - api

networks:
    uw_postgis_net:
      driver: overlay
      external: true
      driver_opts:
        encrypted: "true"
