version: '3'
services:
    db:
        build: 
            context: ./src/db/build
            args:
                db: geocoder
                user: nic
                pw: pass
                states: "WA"
                year: 2017
        ports:
            - "5432:5432"
        networks:
            default:
                aliases:
                    - db

networks:
    default:
        driver: bridge